tasks:
  - init: yarn
    command: yarn serve
  - command: |
      gp open index.js
      gp preview $(gp url 1234)
    openMode: split-right
jetbrains:
  intellij:
    vmoptions: >
      -Dhttp.proxyHost=testhost
      -Dhttp.proxyPort=8080
      -Dhttp.proxyUser=testuser
      -Dhttp.proxyPassword=testpassword
