image:
  file: .gitpod.Dockerfile
tasks:
  - command: |
      sudo tinyproxy
      sudo tail -f /var/log/tinyproxy/tinyproxy.log
  - init: yarn
    command: yarn serve
  - command: |
      gp open index.js
      gp preview $(gp url 1234)
    openMode: split-right
