image:
  file: .gitpod.Dockerfile
tasks:
  - command: |
      sudo tinyproxy
      sudo tail -f /var/log/tinyproxy/tinyproxy.log

jetbrains:
  intellij:
    vmoptions: -Didea.log.debug.categories=#com.intellij.util
